# Generated by Django 5.2.2 on 2025-06-10 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description', max_length=300),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (leave blank to use name)', max_length=200),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(default='#0070f2', help_text='Hex color code', max_length=7),
        ),
    ]
